console.log(" __________________________________________ ");
console.log("|#|       --  ##Report Card##  --       |#|");
console.log("|       ----------------------            |");
console.log("|  Name: Vijay Dodiya                     |");
console.log("|                                         |");
console.log("|  roll_no:  25                           |");
console.log("|                                         |");
console.log("|  school: Jawahar Navodaya Vidhyalaya    |");
console.log("|                                         |");
console.log("|  section:A                              |");
console.log("|                                         |");
console.log("|  grade: A                               |");
console.log("|                                         |");
console.log("|  English 75                             |");
console.log("|                                         |");
console.log("|  Maths 95                               |");
console.log("|                                         |");
console.log("|  Physics 93                             |");
console.log("|                                         |");
console.log("###########################################");
console.log("|------------*******@*******--------------|");